# Generated by Django 3.2.16 on 2023-02-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0007_auto_20171218_1621'),
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
    ]
